pacakges:
    - "projects/vanilla-normalize/**"
    - "projects/vanilla-layout/**"
    - "projects/tailwind-normalize/**"
    - "projects/tailwind-layout/**"
    - "projects/build-excellent-websites/**"
